config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  #/path => controller#method
  # get 'produtos' => 'produtos#index'
  # post '/produtos' => 'produtos#create'
  # get 'produtos/new' => 'produtos#new'
  # delete 'produtos/:id' => 'produtos#destroy', as: :produto
  #resources :produtos gera todas as rotas possíveis
  resources :produtos, only: [:new, :create, :destroy, :edit, :update]
  get '/produtos/busca' => 'produtos#busca', as: :busca_produto
  root 'produtos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/departamento.rb
class Departamento < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord

  belongs_to :departamento
  
  validates :nome, length: {minimum: 5}
  validates :descricao, presence: true
  validates :quantidade, presence: true
  validates :preco, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  def create
    @departamento = Departamento.new(departamento_params)

    if @departamento.save
      redirect_to @departamento, notice: 'Departamento was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /departamentos/1
  def update
    if @departamento.update(departamento_params)
      redirect_to @departamento, notice: 'Departamento was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /departamentos/1
  def destroy
    @departamento.destroy
    redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController

  before_action :set_produto, only: [:edit, :update, :destroy ]
  def index
    @produtos_por_nome =  Produto.order(:nome).limit 5
    @produtos_por_preco = Produto.order(:preco).limit 2
  end

  def new
    @produto = Produto.new
    renderiza :new
  end

  def busca
    @nome_a_buscar = params[:nome]
    if @nome_a_buscar == "*"
      @produtos = Produto.where "nome like '%%'"
    else
      @produtos = Produto.where "nome like ?", "%#{@nome_a_buscar}%"
    end
  end

  def edit
    renderiza :edit
  end

  def update
    if @produto.update produto_params
      redirect_to root_url, notice: 'Produto editado com Sucesso.'
    else
      renderiza :edit
    end
  end

  def create
    @produto = Produto.new produto_params
    if @produto.save
      #flash[:notice] = 'Produto 2222criado com Sucesso.'
      redirect_to root_url, notice: 'Produto criado com Sucesso.'
    else
      renderiza :new
    end
    #redirect_to root_url
  end

  def destroy
    @produto.destroy
    redirect_to root_url, notice: 'Produto excluído com sucesso!'
  end

  private

  def renderiza(view)
    @departamentos = Departamento.all
    render view
  end

  def set_produto
    id = params[:id]
    @produto = Produto.find(id)
  end

  def produto_params
    params.require(:produto).permit :nome, :preco, :descricao, :quantidade, :departamento_id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/departamentos/_form.html.erb
<%= form_with(model: departamento, local: true) do |form| %>
  <% if departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :departamento_nome %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New Departamento</h1>

<%= render 'form', departamento: @departamento %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <title>Loja de Camisetas</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= nav_bar brand: "GeekStore", brand_link: root_url do %>
        <%= form_tag busca_produto_path, method: :get, class: "navbar-form navbar-right" do %>
          <div class="form-group">
              <%= text_field_tag :nome, @nome_a_buscar, class: "form-control" %>
              <%= button_to "Buscar", nil, class: "btn btn-default"%>
          </div>
        <% end %>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/produtos/_form.html.erb
<%= form_for @produto do |f| %>

<div class="form-group">
  <%= f.label :nome %>
  <%= f.text_field :nome, class: "form-control" %>
  <br/>
</div>

<div class="form-group">
  <%= f.label :descricao , 'Descrição' %>
  <%= f.text_area :descricao, class: "form-control", rows: 4 %>
</div>

<div class="form-group">
  <%= f.label :departamento %>
  <%= f.collection_select :departamento_id, @departamentos, :id, :nome, {}, class: "form-control" %>
</div>

<div class="form-inline">
  <div class="form-group">
    <%= f.label :quantidade %>
    <%= f.number_field :quantidade, min: 0, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :preco, 'Preço' %>
    <%= f.number_field :preco, step: 0.01, min: 0, class: "form-control" %>
  </div>
  <%= f.submit texto_da_acao, class: "btn btn-primary" %>
</div>
<br/>
<br/>

<% if @produto && @produto.errors.any? %>
<div id="error_explanation" class="alert alert-danger">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <h4><%= pluralize(@produto.errors.count, "erros") %> encontrados: Verifique o preenchimento!</h4>

  <ul>
    <% @produto.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>

</div>
<% end %>
<% end %>

app/views/produtos/_produto.html.erb

<tr>
  <td><%= produto.nome %></td>
  <td><%= produto.descricao %></td>
  <td><%= produto.preco %></td>
  <!-- <td><%= produto.quantidade %></td> -->
  <td>
    <%= button_to "Remover", produto, method: :delete,  class: "btn btn-danger ",
          data: { confirm: "Tem certeza que deseja remover #{produto.nome}?"} %>
    <!-- <%= link_to "Remover Hum", produto, method: :delete %> -->
    <!-- <%= link_to "Remover Produto", "produtos//#{produto.id}/remove" %> -->
    <!-- <a href="/produtos/<%= produto.id %>/remove">Remover</a> -->
  </td>

  <td>

    <%= button_to "Alterar Produto",  edit_produto_path(produto), method: :get, class: "btn btn-default " %>

  </td>

</tr>

app/views/produtos/busca.html.erb
<table class ="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Preço</th>
      <!-- <th>Quantidade</th> -->
      <th></th>
    </tr>
  </thead>
  <tbody>

      <%= render @produtos %>
      
  </tbody>
</table>

app/views/produtos/edit.html.erb
<%= render partial: "form", locals: {texto_da_acao: 'Editar Produto'} %>

app/views/produtos/index.html.erb
<!-- <%= nav_bar brand: "GeekStore", brand_link: "/produtos" %> -->
<% if notice %>
  <div id="notice" class="alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
  </div>
<% end %>

<table class ="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Preço</th>
      <!-- <th>Quantidade</th> -->
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>

      <%= render partial: "produto", collection: @produtos_por_nome %>

  </tbody>
</table>

<table class="table table-bordered">
  <thead>
    <h2><font color="green"> Melhores Ofertas </font></h2>
    <tr>
      <th>Nome</th>
      <th>Descrição</th>
      <th>Preço</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>

      <%= render @produtos_por_preco %>

  </tbody>
</table>

<%= link_to "Cadastrar Produto", new_produto_path %>

app/views/produtos/new.html.erb
<%= render partial: "form", locals: {texto_da_acao: 'Criar Produto'} %>